### ISSUE TITLE
Erroneous etcd member name log when no backing instance is available

### ISSUE THREAD

**Issue by nicktate** [containership/infrastructure-controller#15]
#### What is the current behavior?
When a new master node is being provisioned, its etcd member representation is added before the actual Kubernetes node is created. Infrastructure controller prints an erroneous log until the backing VM is available.

#### What is the expected behavior?
It should either not log at this point, or print the actual etcd members name.

### Evidence
```
2019-03-07T15:49:59.971Z        INFO    Found etcd member named "" with no corresponding Kubernetes node
```

### Environment
AWS CKE 1.12.x

**Comment by mattkelly** [comment]
Let's just make this level `DEBUG`
