### ISSUE TITLE
Remove cluster nodes not properly backed by a VM

### ISSUE THREAD

**Issue by mikestoltz** [containership/infrastructure-controller#17]
#### Why should this feature be added?
Before removing a VM from a cluster, the cloud provision service attempts to remove the node from the cluster. This can removal can sometimes fail which currently causes the entire scale down operation to about. It would be deal to continue on in this case and have the node retroactively removed from the cluster after the backing VM is deleted.

#### How would you like the feature to work?
A VMs can be retrieved from the `https://provision.containership.io/v3/organizations/:organization_id/clusters/:cluster_id/node-pools/:node_pool_id/nodes/:node_id` endpoint on the provision service. The controller can see that a node has gone into `NotReady` and fetch the endpoint for that node on the provision api. If that route 404s then the backing VM has been removed and that node should be removed from the cluster.

#### What alternatives have been considered?
We have considered attempting a rollback when this fail case is hit on the provision api. However this is currently difficult to convey back to the user, and it is possible to still remove the backing VMs which seems like the better scenario.

**Comment by mattkelly** [comment]
It might be useful to clean up `ClusterStatus` while we're at it (for clusters that have it), since we never run `kubeadm reset`: https://github.com/kubernetes/kubeadm/issues/1312

Basically we'd just be doing everything `kubeadm reset` would be doing.
