### ISSUE TITLE
Add autoscaling components

### ISSUE THREAD

**Issue by normanjoyner** [containership/infrastructure-controller#2]
This should likely be separated out into two parts: one component that is responsible for receiving a webhook, parsing it, and making a scale request (the provision service may reject this if outside of min / max range, but that should be okay), and a component responsible for generating alerts (webhook POSTs) when the configured thresholds are met. As a first pass, we can use resource requests vs available resources as a naive approach, and later integrate something like prometheus alerting (assuming the user is running the prometheus plugin).

Total available resources can be computed from the k8s API for the nodes in the pool, and resource requests can be tallied from all pods running on nodes within the node pool.

**Comment by mattkelly** [comment]
Let's step back and actually define what this should really look like before implementing

**Comment by mattkelly** [comment]
Closing in favor of new issues which will be created over at containership/cerebral.
